version: '3'
services:
  postgresDb:
    image: postgres:13
    container_name: 'postgresDB-RATING-SYSTEM'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'ratingSystemDev'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
  api:
    image: hamburger9/rating-system:0.0.1
    ports:
      - "3000:3000"

     
